import SiteLayout from '@components/SiteLayout'
import Head from "next/head"
import { MoralisProvider } from "react-moralis"
import '../globals.css'

const APP_ID = process.env.NEXT_PUBLIC_APP_ID
const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>joinf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MoralisProvider appId={APP_ID} serverUrl={SERVER_URL}>
        <SiteLayout>
          <Component {...pageProps} />
        </SiteLayout>
      </MoralisProvider>
    </div>
  )
}

export default MyApp
